create extension if not exists pgcrypto;

create table if not exists public.member_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null,
  avatar_url text,
  selected_character_slug text not null check (selected_character_slug in ('yuji','megumi','nobara','gojo','geto')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists one_user_per_character
on public.member_profiles (selected_character_slug);

create table if not exists public.chat_rooms (
  id uuid primary key default gen_random_uuid(),
  title text not null check (char_length(title) between 3 and 60),
  description text not null default '',
  owner_id uuid not null references auth.users(id) on delete cascade,
  is_public boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.chat_members (
  room_id uuid not null references public.chat_rooms(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  character_slug text not null,
  joined_at timestamptz not null default now(),
  primary key (room_id, user_id)
);

create table if not exists public.chat_messages (
  id bigint generated by default as identity primary key,
  room_id uuid not null references public.chat_rooms(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  character_slug text not null,
  body text not null check (char_length(body) between 1 and 1000),
  created_at timestamptz not null default now()
);

alter table public.member_profiles enable row level security;
alter table public.chat_rooms enable row level security;
alter table public.chat_members enable row level security;
alter table public.chat_messages enable row level security;

create policy "Membros autenticados veem perfis" on public.member_profiles for select to authenticated using (true);
create policy "Usuário cria o próprio perfil" on public.member_profiles for insert to authenticated with check (auth.uid() = user_id);
create policy "Usuário atualiza o próprio perfil" on public.member_profiles for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy "Autenticados veem salas públicas" on public.chat_rooms for select to authenticated using (is_public or owner_id = auth.uid());
create policy "Autenticados criam salas" on public.chat_rooms for insert to authenticated with check (owner_id = auth.uid());
create policy "Dono atualiza sala" on public.chat_rooms for update to authenticated using (owner_id = auth.uid());

create policy "Autenticados veem participantes" on public.chat_members for select to authenticated using (true);
create policy "Usuário entra na sala" on public.chat_members for insert to authenticated with check (user_id = auth.uid());
create policy "Usuário sai da sala" on public.chat_members for delete to authenticated using (user_id = auth.uid());

create policy "Membros veem mensagens" on public.chat_messages for select to authenticated
using (exists (select 1 from public.chat_members m where m.room_id = chat_messages.room_id and m.user_id = auth.uid()));
create policy "Membros enviam mensagens" on public.chat_messages for insert to authenticated
with check (user_id = auth.uid() and exists (select 1 from public.chat_members m where m.room_id = chat_messages.room_id and m.user_id = auth.uid() and m.character_slug = chat_messages.character_slug));

do $$ begin
  alter publication supabase_realtime add table public.chat_messages;
exception when duplicate_object then null;
end $$;

create or replace function public.create_chat_room(room_title text, room_description text default '')
returns uuid language plpgsql security invoker set search_path = public as $$
declare new_room_id uuid; chosen_character text;
begin
  select selected_character_slug into chosen_character from member_profiles where user_id = auth.uid();
  if chosen_character is null then raise exception 'Escolha um personagem antes de criar uma sala'; end if;
  insert into chat_rooms (title, description, owner_id) values (room_title, room_description, auth.uid()) returning id into new_room_id;
  insert into chat_members (room_id, user_id, character_slug) values (new_room_id, auth.uid(), chosen_character);
  return new_room_id;
end; $$;

grant execute on function public.create_chat_room(text, text) to authenticated;
